### ISSUE TITLE
'IDeviceInfoProvider' could not be found

### ISSUE THREAD

**Issue by ghost** [episerver/Ektron.Mobile.Providers#3]
I am trying to build the code and I am getting the below error. What package is the IDeviceInfoProvider class in?

Error   CS0246  The type or namespace name 'IDeviceInfoProvider' could not be found (are you missing a using directive or an assembly reference?)   Mobile.Providers.FiftyOneDegrees    C:\Development\51Degrees\Ektron.Mobile.Providers-master\Mobile.Providers.FiftyOneDegrees\FiftyOneDegreesProvider.cs 16

**Comment by anielsud** [comment]
Hey there, there are a couple references to Ektron DLLs in the project. There are hintpaths for the references that assume that you have the Ektron cms 9.1 installed on your system, but you can update the references to point to wherever you have those DLLs - you can copy them from your production webserver if that's easier. They are not distributed with this repo or by nuget though.

Hope that helps!

**Comment by ghost** [comment]
I did copy the dlls locally and updated the references, but IDeviceInfoProvider is not found. In what dll is that interface supposed to be found? I am on Ektron 8.6.
![capture](https://cloud.githubusercontent.com/assets/17862727/14080542/b2667e54-f4ba-11e5-9535-3cbbb78da569.JPG)

**Comment by anielsud** [comment]
Ah, my mistake. In that version, I believe the IDeviceInfoProvider interface is in the ObjectFactory DLL. I'll look into it and get back to you. Sorry about that!

**Comment by anielsud** [comment]
Hey, so taking a look at Ektron 8.6, this provider won't be compatible as is. In that version, detection is done by calling the IWurflProvider defined in the unity config, which implements a single method called GetDeviceInfo. The code here could be modified to work with that, by taking the 51DegreesProvider and changing it to implement the IWurflProvider, then modifying the unity config to point to the new class.

On that version, the workarea UI cannot be redirected to use the new provider unfortunately, but the device detection can be. That means you won't be able to leverage group by device model, or group by operating system. However, grouping by resolution should work.

I'll look into updating some code for that version, but you may also want to consider upgrading to a more recent version.
